
name: Deploy Docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm


      - name: Build Project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run build
          > dist/.nojekyll

      - name: Deploy Project
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          token: ${{ secrets.GITHUB_TOKEN}}
          branch: gh-pages
          folder: dist
